dir_list:
  home: "/Users/awicks/Desktop/Privacy/Track_2/Health-Privacy-Challenge"
  data_splits: "data_splits"
  processed_data: "data/processed"
  figures: "results/figures"
  res_files: "results/files"
  mia_files: "results/mia"

dataset_config:
  name: "onek1k"
  train_count_file: "/Users/awicks/Desktop/Privacy/Track_2/Health-Privacy-Challenge/data/onek1k_annotated_train.h5ad"
  test_count_file:  "/Users/awicks/Desktop/Privacy/Track_2/Health-Privacy-Challenge/data/onek1k_annotated_test.h5ad"
  cell_type_col_name:  "cell_type"
  cell_label_col_name: "cell_label"
  celltypist_model:    "data/meta/downloads/Immune_All_High.pkl"
  random_seed:         28
  membership_label_col: "membership"

generator_name: "nmf_sampler" # "sc_dist" or "nmf_cvae"
generate: true
train:    true
load_from_checkpoint: false

generator_config:
  name:            "nmf_sampler"
  experiment_name: "none"

nmf_sampler_config:
  sample_fraction: 0.1      # fraction of cells to use for NMF & clustering
  seed:            28        # random seed
  sampling_method: "poisson" # or zinb
  n_components:    20        # number of NMF components (K)
  nmf_batch_size:  1000      # batch size for MiniBatchNMF
  n_clusters:      20        # number of clusters in latent space
  n_synth_samples: -1        # -1 = match number of real cells
  proportion_aware: true     # sample clusters by size if true, uniform if false
  output_h5ad:     "/Users/awicks/Desktop/Privacy/Track_2/Health-Privacy-Challenge/data/synthetic_nmf_none.h5ad"

sc_dist_config:
  noise_level: 0.5 # noise level exists, but not used in generation (provided as an example in case you want to use)
  random_seed: 28
  distribution: "Poisson"
  sample_fraction: 0.1 

dp_config:
  # Differential privacy budgets
  eps_nmf:         0.5    # budget for NMF output perturbation
  nmf_noise_scale: 1.0    # scale of Gaussian noise added to H
  eps_kmeans:      2.1    # budget for DP KMeans clustering
  eps_summaries:   0.2    # budget for Laplace noise on cluster summaries
  laplace_scale:   1.0    # multiplier for summary noise scale

evaluator_config:
  random_seed: 28
  subsample_n: 10000

nmf_cvae_config:
  sample_fraction: 0.01
  seed:            28
  n_components:    5
  nmf_batch_size:  1000
  z_dim:           32
  beta:            1.0
  lr:              1e-3
  epochs:          25
  cvae_batch_size: 32
  transform:       "none"
  cell_type_col:   "cell_type"
  device:          "cpu"
  output_h5ad:     "/Users/awicks/Desktop/Privacy/Track_2/Health-Privacy-Challenge/data/synthetic_nmf_cvae.h5ad"
  

attack_model: "sc_domias_baselines"
  